/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Views;

import controller.ListaDeTelevisores;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author derno
 */
public class CrearTelevisor extends javax.swing.JPanel {

    private ListaDeTelevisores televisores;
    public CrearTelevisor(ListaDeTelevisores tv) {
        this.televisores=tv;
        initComponents();
    }
    
    
       private void MostrarJpanel(JPanel p){
        p.setSize(1082,630);   
        p.setLocation(0,0);
        BackgroundCrearTelevisor.removeAll();
        BackgroundCrearTelevisor.add(p,BorderLayout.CENTER);
        BackgroundCrearTelevisor.revalidate();
        BackgroundCrearTelevisor.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundCrearTelevisor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CrearTelevisorTeclado = new javax.swing.JButton();
        CrearTelevisorPrecioPeso = new javax.swing.JButton();
        CrearTelevisorDefecto = new javax.swing.JButton();

        BackgroundCrearTelevisor.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundCrearTelevisor.setPreferredSize(new java.awt.Dimension(1082, 630));

        jPanel2.setBackground(new java.awt.Color(21, 101, 192));

        CrearTelevisorTeclado.setBackground(new java.awt.Color(21, 101, 192));
        CrearTelevisorTeclado.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearTelevisorTeclado.setForeground(new java.awt.Color(255, 255, 255));
        CrearTelevisorTeclado.setText("Crear por teclado");
        CrearTelevisorTeclado.setBorder(null);
        CrearTelevisorTeclado.setBorderPainted(false);
        CrearTelevisorTeclado.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrearTelevisorTeclado.setIconTextGap(13);
        CrearTelevisorTeclado.setInheritsPopupMenu(true);
        CrearTelevisorTeclado.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearTelevisorTecladoActionPerformed(evt);
            }
        });

        CrearTelevisorPrecioPeso.setBackground(new java.awt.Color(21, 101, 192));
        CrearTelevisorPrecioPeso.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearTelevisorPrecioPeso.setForeground(new java.awt.Color(255, 255, 255));
        CrearTelevisorPrecioPeso.setText("Crear con precio y peso");
        CrearTelevisorPrecioPeso.setBorder(null);
        CrearTelevisorPrecioPeso.setBorderPainted(false);
        CrearTelevisorPrecioPeso.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrearTelevisorPrecioPeso.setIconTextGap(13);
        CrearTelevisorPrecioPeso.setInheritsPopupMenu(true);
        CrearTelevisorPrecioPeso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearTelevisorPrecioPesoActionPerformed(evt);
            }
        });

        CrearTelevisorDefecto.setBackground(new java.awt.Color(21, 101, 192));
        CrearTelevisorDefecto.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearTelevisorDefecto.setForeground(new java.awt.Color(255, 255, 255));
        CrearTelevisorDefecto.setText("Crear por defecto");
        CrearTelevisorDefecto.setBorder(null);
        CrearTelevisorDefecto.setBorderPainted(false);
        CrearTelevisorDefecto.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrearTelevisorDefecto.setIconTextGap(13);
        CrearTelevisorDefecto.setInheritsPopupMenu(true);
        CrearTelevisorDefecto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearTelevisorDefectoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearTelevisorTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(CrearTelevisorPrecioPeso, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(CrearTelevisorDefecto, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearTelevisorTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CrearTelevisorPrecioPeso, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(CrearTelevisorDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundCrearTelevisorLayout = new javax.swing.GroupLayout(BackgroundCrearTelevisor);
        BackgroundCrearTelevisor.setLayout(BackgroundCrearTelevisorLayout);
        BackgroundCrearTelevisorLayout.setHorizontalGroup(
            BackgroundCrearTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearTelevisorLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(729, Short.MAX_VALUE))
        );
        BackgroundCrearTelevisorLayout.setVerticalGroup(
            BackgroundCrearTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearTelevisorLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearTelevisorTecladoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearTelevisorTecladoActionPerformed
        MostrarJpanel (new TelevisorTeclado(televisores));
    }//GEN-LAST:event_CrearTelevisorTecladoActionPerformed

    private void CrearTelevisorPrecioPesoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearTelevisorPrecioPesoActionPerformed
        MostrarJpanel (new TelevisorPrecioPeso(televisores));
    }//GEN-LAST:event_CrearTelevisorPrecioPesoActionPerformed

    private void CrearTelevisorDefectoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearTelevisorDefectoActionPerformed
       boolean resultado = televisores.crearTelevisor();
        if (resultado) {
            JOptionPane.showMessageDialog(null, "Televisor registrado con éxito.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CrearTelevisorDefectoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundCrearTelevisor;
    private javax.swing.JButton CrearTelevisorDefecto;
    private javax.swing.JButton CrearTelevisorPrecioPeso;
    private javax.swing.JButton CrearTelevisorTeclado;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
