/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Views;

import controller.ListaDeTelevisores;
import java.awt.BorderLayout;
import javax.swing.JOptionPane;
import javax.swing.JPanel;

/**
 *
 * @author derno
 */
public class CrearTelevisor extends javax.swing.JPanel {

    private ListaDeTelevisores televisores;
    public CrearTelevisor(ListaDeTelevisores tv) {
        this.televisores=tv;
        initComponents();
    }
    
    
       private void MostrarJpanel(JPanel p){
        p.setSize(1082,630);   
        p.setLocation(0,0);
        BackgroundCrearTelevisor.removeAll();
        BackgroundCrearTelevisor.add(p,BorderLayout.CENTER);
        BackgroundCrearTelevisor.revalidate();
        BackgroundCrearTelevisor.repaint();
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundCrearTelevisor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CrearTelevisorDefecto = new javax.swing.JLabel();
        CrearTelevisorTeclado = new javax.swing.JLabel();
        CrearTelevisorPesoPrecio = new javax.swing.JLabel();

        BackgroundCrearTelevisor.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundCrearTelevisor.setPreferredSize(new java.awt.Dimension(1082, 630));

        jPanel2.setBackground(new java.awt.Color(21, 101, 192));

        CrearTelevisorDefecto.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CrearTelevisorDefecto.setForeground(new java.awt.Color(255, 255, 255));
        CrearTelevisorDefecto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearTelevisorDefecto.setText("Crear por defecto");
        CrearTelevisorDefecto.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearTelevisorDefecto.setIconTextGap(35);
        CrearTelevisorDefecto.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CrearTelevisorDefectoMouseMoved(evt);
            }
        });
        CrearTelevisorDefecto.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearTelevisorDefectoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearTelevisorDefectoMouseExited(evt);
            }
        });

        CrearTelevisorTeclado.setBackground(new java.awt.Color(255, 255, 255));
        CrearTelevisorTeclado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CrearTelevisorTeclado.setForeground(new java.awt.Color(255, 255, 255));
        CrearTelevisorTeclado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearTelevisorTeclado.setText("Crear por teclado");
        CrearTelevisorTeclado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearTelevisorTeclado.setIconTextGap(35);
        CrearTelevisorTeclado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CrearTelevisorTecladoMouseMoved(evt);
            }
        });
        CrearTelevisorTeclado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearTelevisorTecladoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearTelevisorTecladoMouseExited(evt);
            }
        });

        CrearTelevisorPesoPrecio.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CrearTelevisorPesoPrecio.setForeground(new java.awt.Color(255, 255, 255));
        CrearTelevisorPesoPrecio.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearTelevisorPesoPrecio.setText("Crear con precio y peso");
        CrearTelevisorPesoPrecio.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearTelevisorPesoPrecio.setIconTextGap(35);
        CrearTelevisorPesoPrecio.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CrearTelevisorPesoPrecioMouseMoved(evt);
            }
        });
        CrearTelevisorPesoPrecio.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearTelevisorPesoPrecioMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearTelevisorPesoPrecioMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearTelevisorTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CrearTelevisorPesoPrecio, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(CrearTelevisorDefecto, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(CrearTelevisorTeclado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(CrearTelevisorPesoPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(CrearTelevisorDefecto, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundCrearTelevisorLayout = new javax.swing.GroupLayout(BackgroundCrearTelevisor);
        BackgroundCrearTelevisor.setLayout(BackgroundCrearTelevisorLayout);
        BackgroundCrearTelevisorLayout.setHorizontalGroup(
            BackgroundCrearTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundCrearTelevisorLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(759, Short.MAX_VALUE))
        );
        BackgroundCrearTelevisorLayout.setVerticalGroup(
            BackgroundCrearTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundCrearTelevisorLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundCrearTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearTelevisorDefectoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorDefectoMouseMoved

    }//GEN-LAST:event_CrearTelevisorDefectoMouseMoved

    private void CrearTelevisorDefectoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorDefectoMouseClicked
        boolean resultado = televisores.crearTelevisor();
        if (resultado) {
            JOptionPane.showMessageDialog(null, "Televisor registrado con éxito.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        }
    }//GEN-LAST:event_CrearTelevisorDefectoMouseClicked

    private void CrearTelevisorDefectoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorDefectoMouseExited

    }//GEN-LAST:event_CrearTelevisorDefectoMouseExited

    private void CrearTelevisorTecladoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorTecladoMouseMoved

    }//GEN-LAST:event_CrearTelevisorTecladoMouseMoved

    private void CrearTelevisorTecladoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorTecladoMouseClicked
        MostrarJpanel (new TelevisorTeclado(televisores));
    }//GEN-LAST:event_CrearTelevisorTecladoMouseClicked

    private void CrearTelevisorTecladoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorTecladoMouseExited

    }//GEN-LAST:event_CrearTelevisorTecladoMouseExited

    private void CrearTelevisorPesoPrecioMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorPesoPrecioMouseMoved

    }//GEN-LAST:event_CrearTelevisorPesoPrecioMouseMoved

    private void CrearTelevisorPesoPrecioMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorPesoPrecioMouseClicked
        MostrarJpanel (new TelevisorPrecioPeso(televisores));
    }//GEN-LAST:event_CrearTelevisorPesoPrecioMouseClicked

    private void CrearTelevisorPesoPrecioMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorPesoPrecioMouseExited

    }//GEN-LAST:event_CrearTelevisorPesoPrecioMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundCrearTelevisor;
    private javax.swing.JLabel CrearTelevisorDefecto;
    private javax.swing.JLabel CrearTelevisorPesoPrecio;
    private javax.swing.JLabel CrearTelevisorTeclado;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
