/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Views;

import View.Views.Lavadora.*;
import controller.ListaDeLavadoras;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author derno
 */
public class Lavadora extends javax.swing.JPanel {

    private ListaDeLavadoras lavadoras;
    
    public Lavadora(ListaDeLavadoras lavadora ) {
        this.lavadoras=lavadora;
        initComponents();
    }
    
    
    private void MostrarJpanel(JPanel p){
        p.setSize(1082,630);   
        p.setLocation(0,0);
        BackgroundLavadora.removeAll();
        BackgroundLavadora.add(p,BorderLayout.CENTER);
        BackgroundLavadora.revalidate();
        BackgroundLavadora.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundLavadora = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        EliminarLavadora = new javax.swing.JLabel();
        CrearLavadora = new javax.swing.JLabel();
        ModificarLavadora = new javax.swing.JLabel();
        CalcularTiempoLavado = new javax.swing.JLabel();

        BackgroundLavadora.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundLavadora.setPreferredSize(new java.awt.Dimension(1082, 630));

        jPanel2.setBackground(new java.awt.Color(21, 101, 192));

        EliminarLavadora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EliminarLavadora.setForeground(new java.awt.Color(255, 255, 255));
        EliminarLavadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarLavadora.setText("Eliminar Lavadora");
        EliminarLavadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarLavadora.setIconTextGap(35);
        EliminarLavadora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EliminarLavadoraMouseMoved(evt);
            }
        });
        EliminarLavadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarLavadoraMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarLavadoraMouseExited(evt);
            }
        });

        CrearLavadora.setBackground(new java.awt.Color(255, 255, 255));
        CrearLavadora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CrearLavadora.setForeground(new java.awt.Color(255, 255, 255));
        CrearLavadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearLavadora.setText("Crear Lavadora");
        CrearLavadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearLavadora.setIconTextGap(35);
        CrearLavadora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CrearLavadoraMouseMoved(evt);
            }
        });
        CrearLavadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearLavadoraMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearLavadoraMouseExited(evt);
            }
        });

        ModificarLavadora.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModificarLavadora.setForeground(new java.awt.Color(255, 255, 255));
        ModificarLavadora.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ModificarLavadora.setText("Modificar Lavadora");
        ModificarLavadora.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarLavadora.setIconTextGap(35);
        ModificarLavadora.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ModificarLavadoraMouseMoved(evt);
            }
        });
        ModificarLavadora.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarLavadoraMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModificarLavadoraMouseExited(evt);
            }
        });

        CalcularTiempoLavado.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CalcularTiempoLavado.setForeground(new java.awt.Color(255, 255, 255));
        CalcularTiempoLavado.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CalcularTiempoLavado.setText("Calcular Tiempo de Lavado");
        CalcularTiempoLavado.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CalcularTiempoLavado.setIconTextGap(35);
        CalcularTiempoLavado.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CalcularTiempoLavadoMouseMoved(evt);
            }
        });
        CalcularTiempoLavado.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CalcularTiempoLavadoMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CalcularTiempoLavadoMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearLavadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModificarLavadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(EliminarLavadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(CalcularTiempoLavado, javax.swing.GroupLayout.DEFAULT_SIZE, 252, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(20, 20, 20)
                .addComponent(CrearLavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(ModificarLavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(30, 30, 30)
                .addComponent(CalcularTiempoLavado, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addComponent(EliminarLavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20))
        );

        javax.swing.GroupLayout BackgroundLavadoraLayout = new javax.swing.GroupLayout(BackgroundLavadora);
        BackgroundLavadora.setLayout(BackgroundLavadoraLayout);
        BackgroundLavadoraLayout.setHorizontalGroup(
            BackgroundLavadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLavadoraLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(652, Short.MAX_VALUE))
        );
        BackgroundLavadoraLayout.setVerticalGroup(
            BackgroundLavadoraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundLavadoraLayout.createSequentialGroup()
                .addContainerGap(96, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(142, 142, 142))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLavadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLavadora, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarLavadoraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarLavadoraMouseMoved

    }//GEN-LAST:event_EliminarLavadoraMouseMoved

    private void EliminarLavadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarLavadoraMouseClicked
        MostrarJpanel (new EliminarLavadorasLista(lavadoras));
    }//GEN-LAST:event_EliminarLavadoraMouseClicked

    private void EliminarLavadoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarLavadoraMouseExited

    }//GEN-LAST:event_EliminarLavadoraMouseExited

    private void CrearLavadoraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearLavadoraMouseMoved

    }//GEN-LAST:event_CrearLavadoraMouseMoved

    private void CrearLavadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearLavadoraMouseClicked
       MostrarJpanel (new CrearLavadora(lavadoras));
    }//GEN-LAST:event_CrearLavadoraMouseClicked

    private void CrearLavadoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearLavadoraMouseExited

    }//GEN-LAST:event_CrearLavadoraMouseExited

    private void ModificarLavadoraMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarLavadoraMouseMoved

    }//GEN-LAST:event_ModificarLavadoraMouseMoved

    private void ModificarLavadoraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarLavadoraMouseClicked
         MostrarJpanel (new ModificarLavadorasLista(lavadoras));
    }//GEN-LAST:event_ModificarLavadoraMouseClicked

    private void ModificarLavadoraMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarLavadoraMouseExited

    }//GEN-LAST:event_ModificarLavadoraMouseExited

    private void CalcularTiempoLavadoMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularTiempoLavadoMouseMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcularTiempoLavadoMouseMoved

    private void CalcularTiempoLavadoMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularTiempoLavadoMouseClicked
        MostrarJpanel (new TiempodeLavado(lavadoras));
    }//GEN-LAST:event_CalcularTiempoLavadoMouseClicked

    private void CalcularTiempoLavadoMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CalcularTiempoLavadoMouseExited
        // TODO add your handling code here:
    }//GEN-LAST:event_CalcularTiempoLavadoMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundLavadora;
    private javax.swing.JLabel CalcularTiempoLavado;
    private javax.swing.JLabel CrearLavadora;
    private javax.swing.JLabel EliminarLavadora;
    private javax.swing.JLabel ModificarLavadora;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
