/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Views;

import View.Views.Lavadora.*;
import controller.ListaDeLavadoras;
import javax.swing.JOptionPane;
import model.Lavadora;

/**
 *
 * @author derno
 */
public class LavadoraTeclado extends javax.swing.JPanel {

    private ListaDeLavadoras listaDeLavadoras;
    
    public LavadoraTeclado(ListaDeLavadoras lavadora) {
        this.listaDeLavadoras=lavadora;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundLavadoraTeclado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apPLbl2 = new javax.swing.JLabel();
        CrearLavadora = new javax.swing.JButton();
        nameLbl1 = new javax.swing.JLabel();
        PrecioLabel = new javax.swing.JTextField();
        apPLbl1 = new javax.swing.JLabel();
        CargaLabel = new javax.swing.JTextField();
        apMLbl1 = new javax.swing.JLabel();
        nameLbl2 = new javax.swing.JLabel();
        PesoLabel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ComboBoxColor = new javax.swing.JComboBox<>();
        ComboBoxConsumo = new javax.swing.JComboBox<>();

        BackgroundLavadoraTeclado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("¡Bienvendio!");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Por favor, ingrese los datos para poder crear la Lavadora: ");

        apPLbl2.setText("Peso");

        CrearLavadora.setBackground(new java.awt.Color(18, 90, 173));
        CrearLavadora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearLavadora.setForeground(new java.awt.Color(255, 255, 255));
        CrearLavadora.setText("Crear");
        CrearLavadora.setBorderPainted(false);
        CrearLavadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrearLavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearLavadoraActionPerformed(evt);
            }
        });

        nameLbl1.setText("Precio Base");

        apPLbl1.setText("Color");

        apMLbl1.setText("Consumo Energetico");

        nameLbl2.setText("Carga");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        ComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Azul", "Rojo ", "Gris", " " }));

        ComboBoxConsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F" }));

        javax.swing.GroupLayout BackgroundLavadoraTecladoLayout = new javax.swing.GroupLayout(BackgroundLavadoraTeclado);
        BackgroundLavadoraTeclado.setLayout(BackgroundLavadoraTecladoLayout);
        BackgroundLavadoraTecladoLayout.setHorizontalGroup(
            BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1004, 1004, 1004))
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(554, 554, 554))
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecioLabel)
                            .addComponent(nameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apPLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apMLbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                                .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apPLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                                .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CargaLabel)
                                        .addComponent(CrearLavadora, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                                    .addComponent(PesoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        BackgroundLavadoraTecladoLayout.setVerticalGroup(
            BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(27, 27, 27)
                .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(nameLbl1)
                        .addGap(15, 15, 15)
                        .addComponent(PrecioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(apPLbl1)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(apMLbl1)
                        .addGap(15, 15, 15)
                        .addComponent(ComboBoxConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(apPLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PesoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(nameLbl2)
                        .addGap(15, 15, 15)
                        .addComponent(CargaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37)
                        .addComponent(CrearLavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(243, Short.MAX_VALUE))
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(118, 118, 118))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLavadoraTeclado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLavadoraTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearLavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearLavadoraActionPerformed
        String valorPrecio = PrecioLabel.getText();
        String valorPeso = PesoLabel.getText();
        String valorCarga = CargaLabel.getText();
        String valorColor = ComboBoxColor.getSelectedItem().toString();
        String valorConsumo = ComboBoxConsumo.getSelectedItem().toString();

        boolean resultado = listaDeLavadoras.crearLavadora(valorPrecio, valorColor, valorConsumo, valorPeso, valorCarga);
        if (resultado) {
            JOptionPane.showMessageDialog(null, "Lavadora registrada con éxito.", "Registro Exitoso", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error al registrar la lavadora. Verifique los datos ingresados.", "Error", JOptionPane.ERROR_MESSAGE);
        }

    }//GEN-LAST:event_CrearLavadoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundLavadoraTeclado;
    private javax.swing.JTextField CargaLabel;
    private javax.swing.JComboBox<String> ComboBoxColor;
    private javax.swing.JComboBox<String> ComboBoxConsumo;
    private javax.swing.JButton CrearLavadora;
    private javax.swing.JTextField PesoLabel;
    private javax.swing.JTextField PrecioLabel;
    private javax.swing.JLabel apMLbl1;
    private javax.swing.JLabel apPLbl1;
    private javax.swing.JLabel apPLbl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel nameLbl2;
    // End of variables declaration//GEN-END:variables
}
