/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Views;

import controller.ListaDeLavadoras;
import javax.swing.JOptionPane;
import model.Lavadora;

/**
 *
 * @author derno
 */
public class ModificarLavadora extends javax.swing.JPanel {

    private ListaDeLavadoras listaDeLavadoras;
    private Lavadora lavadora;
    
    public ModificarLavadora(ListaDeLavadoras listaDeLavadoras, Lavadora lavadora) {
        this.listaDeLavadoras = listaDeLavadoras;
        this.lavadora = lavadora;
        initComponents();
        cargarDatosLavadora();
    }
    
    private void cargarDatosLavadora() {
        PrecioLabel.setText(String.valueOf(lavadora.getPrecioBase()));
        PesoLabel.setText(String.valueOf(lavadora.getPeso()));
        CargaLabel.setText(String.valueOf(lavadora.getCarga()));
        ComboBoxColor.setSelectedItem(lavadora.getColor());
        ComboBoxConsumo.setSelectedItem(String.valueOf(lavadora.getConsumoEnergetico()));
    }
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundLavadoraTeclado = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        apPLbl2 = new javax.swing.JLabel();
        ModificarLavadora = new javax.swing.JButton();
        nameLbl1 = new javax.swing.JLabel();
        PrecioLabel = new javax.swing.JTextField();
        apPLbl1 = new javax.swing.JLabel();
        CargaLabel = new javax.swing.JTextField();
        apMLbl1 = new javax.swing.JLabel();
        nameLbl2 = new javax.swing.JLabel();
        PesoLabel = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        ComboBoxColor = new javax.swing.JComboBox<>();
        ComboBoxConsumo = new javax.swing.JComboBox<>();

        BackgroundLavadoraTeclado.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        jLabel1.setText("Modificar Lavadora");

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        jLabel2.setText("Por favor, ingrese los datos para poder modificar la Lavadora: ");

        apPLbl2.setText("Peso");

        ModificarLavadora.setBackground(new java.awt.Color(18, 90, 173));
        ModificarLavadora.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ModificarLavadora.setForeground(new java.awt.Color(255, 255, 255));
        ModificarLavadora.setText("Guardar");
        ModificarLavadora.setBorderPainted(false);
        ModificarLavadora.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ModificarLavadora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarLavadoraActionPerformed(evt);
            }
        });

        nameLbl1.setText("Precio Base");

        apPLbl1.setText("Color");

        apMLbl1.setText("Consumo Energetico");

        nameLbl2.setText("Carga");

        jSeparator1.setForeground(new java.awt.Color(204, 204, 204));
        jSeparator1.setOrientation(javax.swing.SwingConstants.VERTICAL);
        jSeparator1.setPreferredSize(new java.awt.Dimension(200, 10));

        ComboBoxColor.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Blanco", "Negro", "Azul", "Rojo ", "Gris", " " }));

        ComboBoxConsumo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "A", "B", "C", "D", "E", "F" }));

        javax.swing.GroupLayout BackgroundLavadoraTecladoLayout = new javax.swing.GroupLayout(BackgroundLavadoraTeclado);
        BackgroundLavadoraTeclado.setLayout(BackgroundLavadoraTecladoLayout);
        BackgroundLavadoraTecladoLayout.setHorizontalGroup(
            BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(1004, 1004, 1004))
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(554, 554, 554))
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(PrecioLabel)
                            .addComponent(nameLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apPLbl1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(apMLbl1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                                .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ComboBoxConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(ComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 10, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(apPLbl2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                                .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addComponent(nameLbl2, javax.swing.GroupLayout.PREFERRED_SIZE, 76, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(CargaLabel)
                                        .addComponent(ModificarLavadora, javax.swing.GroupLayout.DEFAULT_SIZE, 454, Short.MAX_VALUE))
                                    .addComponent(PesoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 454, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        BackgroundLavadoraTecladoLayout.setVerticalGroup(
            BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addComponent(jLabel2)
                .addGap(27, 27, 27)
                .addGroup(BackgroundLavadoraTecladoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(nameLbl1)
                        .addGap(15, 15, 15)
                        .addComponent(PrecioLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(apPLbl1)
                        .addGap(18, 18, 18)
                        .addComponent(ComboBoxColor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)
                        .addComponent(apMLbl1)
                        .addGap(15, 15, 15)
                        .addComponent(ComboBoxConsumo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(apPLbl2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(PesoLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(33, 33, 33)
                        .addComponent(nameLbl2)
                        .addGap(15, 15, 15)
                        .addComponent(CargaLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(61, 61, 61)
                        .addComponent(ModificarLavadora, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addContainerGap(219, Short.MAX_VALUE))
                    .addGroup(BackgroundLavadoraTecladoLayout.createSequentialGroup()
                        .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGap(118, 118, 118))))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLavadoraTeclado, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 1082, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundLavadoraTeclado, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void ModificarLavadoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarLavadoraActionPerformed
        String valorPrecio = PrecioLabel.getText();
        String valorPeso = PesoLabel.getText();
        String valorCarga = CargaLabel.getText();
        String valorColor = ComboBoxColor.getSelectedItem().toString();
        String valorConsumo = ComboBoxConsumo.getSelectedItem().toString();

        boolean resultado = listaDeLavadoras.modificarLavadora(lavadora.getId(), valorPrecio, valorColor, valorConsumo, valorPeso, valorCarga);
        if (resultado) {
            JOptionPane.showMessageDialog(null, "Lavadora modificada con éxito.", "Modificación Exitosa", JOptionPane.INFORMATION_MESSAGE);
        } else {
            JOptionPane.showMessageDialog(null, "Error al modificar la lavadora. Verifique los datos ingresados.", "Error", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_ModificarLavadoraActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundLavadoraTeclado;
    private javax.swing.JTextField CargaLabel;
    private javax.swing.JComboBox<String> ComboBoxColor;
    private javax.swing.JComboBox<String> ComboBoxConsumo;
    private javax.swing.JButton ModificarLavadora;
    private javax.swing.JTextField PesoLabel;
    private javax.swing.JTextField PrecioLabel;
    private javax.swing.JLabel apMLbl1;
    private javax.swing.JLabel apPLbl1;
    private javax.swing.JLabel apPLbl2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JLabel nameLbl1;
    private javax.swing.JLabel nameLbl2;
    // End of variables declaration//GEN-END:variables
}
