/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View.Views;

import java.awt.Color;
import java.awt.event.ActionEvent;
import javax.swing.Timer;

/**
 *
 * @author derno
 */
public class PantallaCarga extends javax.swing.JFrame {

    /**
     * Creates new form PantallaCarga
     */
    public PantallaCarga() {
        initComponents();
        pbCargaIniciado();
        setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        Background = new javax.swing.JPanel();
        pbCarga = new javax.swing.JProgressBar();
        backgroundlogo = new javax.swing.JPanel();
        lOGO = new javax.swing.JLabel();


        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Background.setBackground(new java.awt.Color(18, 90, 173));
        Background.setForeground(new java.awt.Color(255, 255, 255));
        Background.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        Background.add(pbCarga, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 280, 370, 30));

        backgroundlogo.setBackground(new java.awt.Color(23, 29, 35));

        lOGO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/Logo Carga.png"))); // NOI18N

        javax.swing.GroupLayout backgroundlogoLayout = new javax.swing.GroupLayout(backgroundlogo);
        backgroundlogo.setLayout(backgroundlogoLayout);
        backgroundlogoLayout.setHorizontalGroup(
            backgroundlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundlogoLayout.createSequentialGroup()
                .addGap(135, 135, 135)
                .addComponent(lOGO)
                .addContainerGap(135, Short.MAX_VALUE))
        );
        backgroundlogoLayout.setVerticalGroup(
            backgroundlogoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(backgroundlogoLayout.createSequentialGroup()
                .addContainerGap(49, Short.MAX_VALUE)
                .addComponent(lOGO)
                .addGap(41, 41, 41))
        );

        Background.add(backgroundlogo, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 70, 370, 190));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 737, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(Background, javax.swing.GroupLayout.DEFAULT_SIZE, 409, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
    
    private void pbCargaIniciado(){
        Timer mTimer = new Timer(50, (ActionEvent e) -> {
            if (pbCarga.getValue() < 100) {
                pbCarga.setValue(pbCarga.getValue() + 1);
                pbCarga.setBackground(Color.BLUE);
                pbCarga.setStringPainted(true);
                pbCarga.setString("Cargando..." + pbCarga.getValue() + "%");
            } else {
                ((Timer)e.getSource()).stop();
            }
        });
        mTimer.start();
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (Exception ex) {
            java.util.logging.Logger.getLogger(PantallaCarga.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }

        java.awt.EventQueue.invokeLater(() -> new PantallaCarga().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Background;
    private javax.swing.JPanel backgroundlogo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lOGO;
    private javax.swing.JProgressBar pbCarga;
    // End of variables declaration//GEN-END:variables

}