/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Views;

import controller.ListaDeTelevisores;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author derno
 */
public class Televisor extends javax.swing.JPanel {

    
    private ListaDeTelevisores televisores;
    public Televisor(ListaDeTelevisores tv) {
        this.televisores=tv;
        initComponents();
    }
    
    
      private void MostrarJpanel(JPanel p){
        p.setSize(1082,630);   
        p.setLocation(0,0);
        BackgroundTelevisor.removeAll();
        BackgroundTelevisor.add(p,BorderLayout.CENTER);
        BackgroundTelevisor.revalidate();
        BackgroundTelevisor.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundTelevisor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        CrearTelevisor = new javax.swing.JButton();
        ModificarTelevisor = new javax.swing.JButton();
        Eliminartelevisor = new javax.swing.JButton();

        BackgroundTelevisor.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundTelevisor.setPreferredSize(new java.awt.Dimension(1082, 630));

        jPanel2.setBackground(new java.awt.Color(21, 101, 192));

        CrearTelevisor.setBackground(new java.awt.Color(21, 101, 192));
        CrearTelevisor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        CrearTelevisor.setForeground(new java.awt.Color(255, 255, 255));
        CrearTelevisor.setText("Crear televisor");
        CrearTelevisor.setBorder(null);
        CrearTelevisor.setBorderPainted(false);
        CrearTelevisor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        CrearTelevisor.setIconTextGap(13);
        CrearTelevisor.setInheritsPopupMenu(true);
        CrearTelevisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CrearTelevisorActionPerformed(evt);
            }
        });

        ModificarTelevisor.setBackground(new java.awt.Color(21, 101, 192));
        ModificarTelevisor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        ModificarTelevisor.setForeground(new java.awt.Color(255, 255, 255));
        ModificarTelevisor.setText("Modificar televisor");
        ModificarTelevisor.setBorder(null);
        ModificarTelevisor.setBorderPainted(false);
        ModificarTelevisor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        ModificarTelevisor.setIconTextGap(13);
        ModificarTelevisor.setInheritsPopupMenu(true);
        ModificarTelevisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ModificarTelevisorActionPerformed(evt);
            }
        });

        Eliminartelevisor.setBackground(new java.awt.Color(21, 101, 192));
        Eliminartelevisor.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        Eliminartelevisor.setForeground(new java.awt.Color(255, 255, 255));
        Eliminartelevisor.setText("Eliminar televisor");
        Eliminartelevisor.setBorder(null);
        Eliminartelevisor.setBorderPainted(false);
        Eliminartelevisor.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        Eliminartelevisor.setIconTextGap(13);
        Eliminartelevisor.setInheritsPopupMenu(true);
        Eliminartelevisor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                EliminartelevisorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(ModificarTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(Eliminartelevisor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(CrearTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(ModificarTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(Eliminartelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundTelevisorLayout = new javax.swing.GroupLayout(BackgroundTelevisor);
        BackgroundTelevisor.setLayout(BackgroundTelevisorLayout);
        BackgroundTelevisorLayout.setHorizontalGroup(
            BackgroundTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundTelevisorLayout.createSequentialGroup()
                .addGap(196, 196, 196)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(729, Short.MAX_VALUE))
        );
        BackgroundTelevisorLayout.setVerticalGroup(
            BackgroundTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundTelevisorLayout.createSequentialGroup()
                .addGap(185, 185, 185)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(227, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void CrearTelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CrearTelevisorActionPerformed
       MostrarJpanel (new CrearTelevisor(televisores));
    }//GEN-LAST:event_CrearTelevisorActionPerformed

    private void ModificarTelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ModificarTelevisorActionPerformed
        MostrarJpanel (new ModificarTelevisoresLista(televisores));
    }//GEN-LAST:event_ModificarTelevisorActionPerformed

    private void EliminartelevisorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_EliminartelevisorActionPerformed
        MostrarJpanel (new EliminarTelevisoresLista(televisores));
    }//GEN-LAST:event_EliminartelevisorActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundTelevisor;
    private javax.swing.JButton CrearTelevisor;
    private javax.swing.JButton Eliminartelevisor;
    private javax.swing.JButton ModificarTelevisor;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
