/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package View.Views;

import controller.ListaDeTelevisores;
import java.awt.BorderLayout;
import javax.swing.JPanel;

/**
 *
 * @author derno
 */
public class Televisor extends javax.swing.JPanel {

    
    private ListaDeTelevisores televisores;
    public Televisor(ListaDeTelevisores tv) {
        this.televisores=tv;
        initComponents();
    }
    
    
      private void MostrarJpanel(JPanel p){
        p.setSize(1082,630);   
        p.setLocation(0,0);
        BackgroundTelevisor.removeAll();
        BackgroundTelevisor.add(p,BorderLayout.CENTER);
        BackgroundTelevisor.revalidate();
        BackgroundTelevisor.repaint();
    }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        BackgroundTelevisor = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        EliminarTelevisor = new javax.swing.JLabel();
        CrearTelevisor = new javax.swing.JLabel();
        ModificarTelevisor = new javax.swing.JLabel();

        BackgroundTelevisor.setBackground(new java.awt.Color(255, 255, 255));
        BackgroundTelevisor.setPreferredSize(new java.awt.Dimension(1082, 630));

        jPanel2.setBackground(new java.awt.Color(21, 101, 192));

        EliminarTelevisor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        EliminarTelevisor.setForeground(new java.awt.Color(255, 255, 255));
        EliminarTelevisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        EliminarTelevisor.setText("Eliminar Televisor");
        EliminarTelevisor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        EliminarTelevisor.setIconTextGap(35);
        EliminarTelevisor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                EliminarTelevisorMouseMoved(evt);
            }
        });
        EliminarTelevisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                EliminarTelevisorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                EliminarTelevisorMouseExited(evt);
            }
        });

        CrearTelevisor.setBackground(new java.awt.Color(255, 255, 255));
        CrearTelevisor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        CrearTelevisor.setForeground(new java.awt.Color(255, 255, 255));
        CrearTelevisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        CrearTelevisor.setText("Crear Televisor");
        CrearTelevisor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        CrearTelevisor.setIconTextGap(35);
        CrearTelevisor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                CrearTelevisorMouseMoved(evt);
            }
        });
        CrearTelevisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CrearTelevisorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                CrearTelevisorMouseExited(evt);
            }
        });

        ModificarTelevisor.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        ModificarTelevisor.setForeground(new java.awt.Color(255, 255, 255));
        ModificarTelevisor.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        ModificarTelevisor.setText("Modificar Televisor");
        ModificarTelevisor.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        ModificarTelevisor.setIconTextGap(35);
        ModificarTelevisor.addMouseMotionListener(new java.awt.event.MouseMotionAdapter() {
            public void mouseMoved(java.awt.event.MouseEvent evt) {
                ModificarTelevisorMouseMoved(evt);
            }
        });
        ModificarTelevisor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                ModificarTelevisorMouseClicked(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                ModificarTelevisorMouseExited(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(CrearTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(ModificarTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 258, Short.MAX_VALUE)
                    .addComponent(EliminarTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(80, 80, 80)
                .addComponent(CrearTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(ModificarTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(45, 45, 45)
                .addComponent(EliminarTelevisor, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(80, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout BackgroundTelevisorLayout = new javax.swing.GroupLayout(BackgroundTelevisor);
        BackgroundTelevisor.setLayout(BackgroundTelevisorLayout);
        BackgroundTelevisorLayout.setHorizontalGroup(
            BackgroundTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(BackgroundTelevisorLayout.createSequentialGroup()
                .addGap(166, 166, 166)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(759, Short.MAX_VALUE))
        );
        BackgroundTelevisorLayout.setVerticalGroup(
            BackgroundTelevisorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, BackgroundTelevisorLayout.createSequentialGroup()
                .addContainerGap(92, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(82, 82, 82))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 1195, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(BackgroundTelevisor, javax.swing.GroupLayout.DEFAULT_SIZE, 616, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void EliminarTelevisorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTelevisorMouseMoved

    }//GEN-LAST:event_EliminarTelevisorMouseMoved

    private void EliminarTelevisorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTelevisorMouseClicked
        MostrarJpanel (new EliminarTelevisoresLista(televisores));
    }//GEN-LAST:event_EliminarTelevisorMouseClicked

    private void EliminarTelevisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_EliminarTelevisorMouseExited

    }//GEN-LAST:event_EliminarTelevisorMouseExited

    private void CrearTelevisorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorMouseMoved

    }//GEN-LAST:event_CrearTelevisorMouseMoved

    private void CrearTelevisorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorMouseClicked
       MostrarJpanel (new CrearTelevisor(televisores));
    }//GEN-LAST:event_CrearTelevisorMouseClicked

    private void CrearTelevisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CrearTelevisorMouseExited

    }//GEN-LAST:event_CrearTelevisorMouseExited

    private void ModificarTelevisorMouseMoved(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarTelevisorMouseMoved

    }//GEN-LAST:event_ModificarTelevisorMouseMoved

    private void ModificarTelevisorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarTelevisorMouseClicked
         MostrarJpanel (new ModificarTelevisoresLista(televisores));
    }//GEN-LAST:event_ModificarTelevisorMouseClicked

    private void ModificarTelevisorMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_ModificarTelevisorMouseExited

    }//GEN-LAST:event_ModificarTelevisorMouseExited


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel BackgroundTelevisor;
    private javax.swing.JLabel CrearTelevisor;
    private javax.swing.JLabel EliminarTelevisor;
    private javax.swing.JLabel ModificarTelevisor;
    private javax.swing.JPanel jPanel2;
    // End of variables declaration//GEN-END:variables
}
